spring:
  datasource:
    url: jdbc:postgresql://dpg-csdnr1o8fa8c73f735ng-a.oregon-postgres.render.com/empire_bicycle_shop_ouu0
    username: empire_bicycle_shop_ouu0_user
    password: jNtvQSkm3QyCBgtmuBM6okj2DzqFi0rv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  mailing:
    frontend:
      activation-url: http://localhost:8080/auth/activate

  password:
    change:
      change-password-url: http://localhost:8080/password/change