spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tumafare
    username: tumafare
    password: tumafare
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  mailing:
    frontend:
      activation-url: http://localhost:8080/auth/activate

  password:
    change:
      change-password-url: http://localhost:8080/password/change