spring:
  application:
    name: tumafare
  profiles:
    active: dev
  mail:
    host: mail.privateemail.com
    port: 465
    username: info@tumafare.com
    password: "@HUNTERmbo83"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp
#  mail:
#    host: smtp.gmail.com
#    port: 465
#    username: tumafareinfo@gmail.com
#    password: elnycxurykidupel
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            trust: "*"
#        starttls:
#          enable: true
#    protocol: smtp

instasend:
  mpesa:
    api-secret: ISSecretKey_live_76efbd91-964e-423d-b54c-febfd46e663b

movesms:
  sms:
    api_key: 6tSWjohsr5Eyfd0vJk9DfqsT6RJbyvUUnGQOyFwWAcBQrp2ZIr

africastalking:
  sms:
    api_key: atsk_1b3457ae6c87c7a8e20aa86f236a94a14bf7f4319e690edfeeff8f27b35e583f872053b6
